<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/5.0.11/css/font-awesome.min.css">
    <title>Drop-down Menu design</title>
</head>

<body>
    <div class="menu-bar">
        <ul>
            <li class="active"><a href="#"><i class="fas fa-users-cog"></i>Administration</a></li>
            <li><a href="#">Le Camping</a></li>
            <li><a href="#">Clients</a></li>
            <li><a href="#">Contact</a></li>
        </ul>
    </div>
</body>

</html>