<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="style.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css">
    <title>Drop-down Menu design</title>
</head>

<body>
    <div class="menu-bar">
        <ul>
            <li class="active"><a href="#"><i class="fas fa-users-cog"></i>Administration</a>
                <div class="sub-menu-1">
                    <ul>
                        <?php if (!$adminSession->isAuthenticated()) : ?>
                        <li><a href="<?= $requestUrl ?>/admin/register" class="item">Admin auth</a></li>
                        <li><a href="<?= $requestUrl ?>/admin/login" class="item">Login</a></li>
                        <?php endif; ?>

                        <?php if ($adminSession->isAuthenticated()) : ?>
                        <li>
                            <a href="#" class="item">Bonjour :
                                <?= ucfirst($adminSession->getName()) ?>&nbsp;&nbsp;
                            </a>
                        </li>
                        <li><a href="<?= $requestUrl ?>/admin/logout" class="item">Logout</a></li>
                        <li><a href="<?= $requestUrl ?>/admin/produits" class="item">Produits</a>
                        </li>
                        <?php endif; ?>
                    </ul>
                </div>
            </li>
            <li><a href="#"><i class="fas fa-campground"></i>Camping</a></li>
            <li><a href="#"><i class="fas fa-users"></i>Clients</a></li>
            <li><a href="#"><i class="fas fa-phone-square-alt"></i>Contact</a></li>
        </ul>
    </div>
</body>

</html>